name: RsNPCX
main: com.smallaswater.npc.NpcMainClass
version: 1.1.3
api:
  - 1.0.9
author: 若水
load: POSTWORLD
commands:
  rnpc:
    description: "NPC主命令"
    usage: "rnpc help"
    permission: RsNPC.npc
permissions:
  RsNPC.npc:
    default: op
    description: "Npc主命令"