name: RsNPC
main: com.smallaswater.npc.RsNPC
version: "2.4.4"
api:
  - "2.0.0"
authors: ["若水", "LT_Name"]
load: POSTWORLD

permissions:
  RsNPC.admin:
    default: op
    description: "RsNPC main command"
  RsNPC.admin.create:
    default: op
    description: "RsNPC create command"
  RsNPC.admin.delete:
    default: op
    description: "RsNPC delete command"
  RsNPC.admin.reload:
    default: op
    description: "RsNPC reload command"
  RsNPC.admin.addroute:
    default: op
    description: "RsNPC Add NPC path point command"